/* College database: BBGM's college names + frequencies (the frequency doubles
   as historical program prestige), conference alignment, and the non-NCAA
   destinations used to replace blank ("None") colleges. */
(function (global) {
	"use strict";

	// Conference base strength (0-100 = average team quality in that league).
	const CONFERENCES = {
		"ACC":            { strength: 91, bids: 7, tier: "high" },
		"SEC":            { strength: 92, bids: 8, tier: "high" },
		"Big Ten":        { strength: 90, bids: 8, tier: "high" },
		"Big 12":         { strength: 91, bids: 7, tier: "high" },
		"Big East":       { strength: 87, bids: 5, tier: "high" },
		"WCC":            { strength: 74, bids: 3, tier: "mid" },
		"American":       { strength: 76, bids: 2, tier: "mid" },
		"Mountain West":  { strength: 76, bids: 3, tier: "mid" },
		"Atlantic 10":    { strength: 75, bids: 2, tier: "mid" },
		"Missouri Valley":{ strength: 69, bids: 1, tier: "mid" },
		"Conference USA": { strength: 65, bids: 1, tier: "mid" },
		"MAC":            { strength: 64, bids: 1, tier: "mid" },
		"Sun Belt":       { strength: 63, bids: 1, tier: "mid" },
		"Big West":       { strength: 63, bids: 1, tier: "mid" },
		"CAA":            { strength: 63, bids: 1, tier: "mid" },
		"WAC":            { strength: 62, bids: 1, tier: "low" },
		"Horizon":        { strength: 61, bids: 1, tier: "low" },
		"MAAC":           { strength: 58, bids: 1, tier: "low" },
		"Southern":       { strength: 59, bids: 1, tier: "low" },
		"Ivy":            { strength: 59, bids: 1, tier: "low" },
		"Ohio Valley":    { strength: 58, bids: 1, tier: "low" },
		"Big Sky":        { strength: 58, bids: 1, tier: "low" },
		"Summit":         { strength: 57, bids: 1, tier: "low" },
		"ASUN":           { strength: 57, bids: 1, tier: "low" },
		"Southland":      { strength: 55, bids: 1, tier: "low" },
		"Big South":      { strength: 55, bids: 1, tier: "low" },
		"Patriot":        { strength: 55, bids: 1, tier: "low" },
		"America East":   { strength: 54, bids: 1, tier: "low" },
		"NEC":            { strength: 50, bids: 1, tier: "low" },
		"SWAC":           { strength: 48, bids: 1, tier: "low" },
		"MEAC":           { strength: 48, bids: 1, tier: "low" },
		// Catch-all for colleges outside the built-in database (league files
		// drift across BBGM versions). Not a real league: no members in
		// byConference, no auto bid — just sane strength for lookups.
		"Independent":    { strength: 62, bids: 0, tier: "mid" },
	};

	// school -> [BBGM frequency, conference]
	const COLLEGES = {
		"Abilene Christian": [0.1, "WAC"],
		"Air Force": [1, "Mountain West"],
		"Akron": [4, "MAC"],
		"Alabama": [28, "SEC"],
		"Alabama A&M": [1, "SWAC"],
		"Alabama State": [2, "SWAC"],
		"Albany": [5, "America East"],
		"Alcorn State": [6, "SWAC"],
		"American University": [2, "Patriot"],
		"Appalachian State": [1, "Sun Belt"],
		"Arizona": [57, "Big 12"],
		"Arizona State": [29, "Big 12"],
		"Arkansas": [33, "SEC"],
		"Arkansas State": [3, "Sun Belt"],
		"Arkansas-Little Rock": [7, "Ohio Valley"],
		"Arkansas-Pine Bluff": [1, "SWAC"],
		"Army": [0.1, "Patriot"],
		"Auburn": [23, "SEC"],
		"Austin Peay": [7, "ASUN"],
		"BYU": [22, "Big 12"],
		"Ball State": [3, "MAC"],
		"Baylor": [19, "Big 12"],
		"Belmont": [1, "Missouri Valley"],
		"Bethune-Cookman": [3, "SWAC"],
		"Binghamton": [0.1, "America East"],
		"Boise State": [6, "Mountain West"],
		"Boston College": [27, "ACC"],
		"Boston University": [6, "Patriot"],
		"Bowling Green": [16, "MAC"],
		"Bradley": [21, "Missouri Valley"],
		"Brown": [2, "Ivy"],
		"Bryant University": [0.1, "America East"],
		"Bucknell": [1, "Patriot"],
		"Buffalo": [1, "MAC"],
		"Butler": [6, "Big East"],
		"Cal Poly": [1, "Big West"],
		"Cal State Bakersfield": [1, "Big West"],
		"Cal State Fullerton": [12, "Big West"],
		"Cal State Northridge": [1, "Big West"],
		"California": [37, "ACC"],
		"California Baptist": [0.1, "WAC"],
		"Campbell": [2, "CAA"],
		"Canisius": [11, "MAAC"],
		"Central Arkansas": [1, "ASUN"],
		"Central Connecticut State": [2, "NEC"],
		"Central Michigan": [8, "MAC"],
		"Charleston": [3, "CAA"],
		"Charleston Southern": [0.1, "Big South"],
		"Charlotte": [8, "American"],
		"Chattanooga": [4, "Southern"],
		"Chicago State": [0.1, "NEC"],
		"Cincinnati": [37, "Big 12"],
		"Citadel": [0.1, "Southern"],
		"Clemson": [20, "ACC"],
		"Cleveland State": [6, "Horizon"],
		"Coastal Carolina": [0.1, "Sun Belt"],
		"Colgate": [4, "Patriot"],
		"Colorado": [25, "Big 12"],
		"Colorado State": [11, "Mountain West"],
		"Columbia": [5, "Ivy"],
		"Connecticut": [37, "Big East"],
		"Coppin State": [2, "MEAC"],
		"Cornell": [3, "Ivy"],
		"Creighton": [16, "Big East"],
		"Dartmouth": [6, "Ivy"],
		"Davidson": [6, "Atlantic 10"],
		"Dayton": [22, "Atlantic 10"],
		"DePaul": [37, "Big East"],
		"Delaware": [0.1, "CAA"],
		"Delaware State": [1, "MEAC"],
		"Denver": [6, "Summit"],
		"Detroit Mercy": [22, "Horizon"],
		"Drake": [14, "Missouri Valley"],
		"Drexel": [3, "CAA"],
		"Duke": [86, "ACC"],
		"Duquesne": [22, "Atlantic 10"],
		"East Carolina": [3, "American"],
		"East Tennessee State": [3, "Southern"],
		"Eastern Illinois": [2, "Ohio Valley"],
		"Eastern Kentucky": [7, "ASUN"],
		"Eastern Michigan": [11, "MAC"],
		"Eastern Washington": [2, "Big Sky"],
		"Elon": [1, "CAA"],
		"Evansville": [5, "Missouri Valley"],
		"Fairfield": [2, "MAAC"],
		"Fairleigh Dickinson": [0.1, "NEC"],
		"Florida": [33, "SEC"],
		"Florida A&M": [4, "SWAC"],
		"Florida Atlantic": [0.1, "American"],
		"Florida Gulf Coast": [1, "ASUN"],
		"Florida International": [2, "Conference USA"],
		"Florida State": [38, "ACC"],
		"Fordham": [11, "Atlantic 10"],
		"Fresno State": [23, "Mountain West"],
		"Furman": [3, "Southern"],
		"Gardner-Webb": [4, "Big South"],
		"George Mason": [3, "Atlantic 10"],
		"George Washington": [13, "Atlantic 10"],
		"Georgetown": [45, "Big East"],
		"Georgia": [22, "SEC"],
		"Georgia Southern": [3, "Sun Belt"],
		"Georgia State": [2, "Sun Belt"],
		"Georgia Tech": [39, "ACC"],
		"Gonzaga": [20, "WCC"],
		"Grambling State": [12, "SWAC"],
		"Grand Canyon": [2, "WAC"],
		"Green Bay": [4, "Horizon"],
		"Hampton": [2, "CAA"],
		"Hartford": [1, "America East"],
		"Harvard": [4, "Ivy"],
		"Hawaii": [8, "Big West"],
		"High Point": [1, "Big South"],
		"Hofstra": [5, "CAA"],
		"Holy Cross": [11, "Patriot"],
		"Houston": [34, "Big 12"],
		"Houston Baptist": [1, "Southland"],
		"Howard": [2, "MEAC"],
		"IUPUI": [1, "Horizon"],
		"Idaho": [4, "Big Sky"],
		"Idaho State": [6, "Big Sky"],
		"Illinois": [44, "Big Ten"],
		"Illinois State": [5, "Missouri Valley"],
		"Illinois-Chicago": [2, "Missouri Valley"],
		"Incarnate Word": [0.1, "Southland"],
		"Indiana": [68, "Big Ten"],
		"Indiana State": [10, "Missouri Valley"],
		"Iona": [6, "MAAC"],
		"Iowa": [32, "Big Ten"],
		"Iowa State": [33, "Big 12"],
		"Jackson State": [14, "SWAC"],
		"Jacksonville": [11, "ASUN"],
		"Jacksonville State": [1, "Conference USA"],
		"James Madison": [2, "Sun Belt"],
		"Kansas": [76, "Big 12"],
		"Kansas City": [1, "Summit"],
		"Kansas State": [26, "Big 12"],
		"Kennesaw State": [0.1, "Conference USA"],
		"Kent State": [3, "MAC"],
		"Kentucky": [116, "SEC"],
		"LIU": [23, "NEC"],
		"LSU": [45, "SEC"],
		"La Salle": [24, "Atlantic 10"],
		"Lafayette": [0.1, "Patriot"],
		"Lamar": [5, "Southland"],
		"Lehigh": [1, "Patriot"],
		"Liberty": [3, "Conference USA"],
		"Lipscomb": [1, "ASUN"],
		"Long Beach State": [20, "Big West"],
		"Longwood": [1, "Big South"],
		"Louisiana Tech": [8, "Conference USA"],
		"Louisiana-Lafayette": [10, "Sun Belt"],
		"Louisiana-Monroe": [6, "Sun Belt"],
		"Louisville": [60, "ACC"],
		"Loyola (MD)": [2, "Patriot"],
		"Loyola Chicago": [16, "Atlantic 10"],
		"Loyola Marymount": [9, "WCC"],
		"Maine": [2, "America East"],
		"Manhattan": [11, "MAAC"],
		"Marist": [1, "MAAC"],
		"Marquette": [40, "Big East"],
		"Marshall": [13, "Sun Belt"],
		"Maryland": [43, "Big Ten"],
		"Maryland-Eastern Shore": [4, "MEAC"],
		"Massachusetts": [8, "Atlantic 10"],
		"Massachusetts-Lowell": [0.1, "America East"],
		"McNeese State": [6, "Southland"],
		"Memphis": [37, "American"],
		"Mercer": [1, "Southern"],
		"Merrimack": [0.1, "NEC"],
		"Miami (FL)": [16, "ACC"],
		"Miami (OH)": [0.1, "MAC"],
		"Michigan": [57, "Big Ten"],
		"Michigan State": [49, "Big Ten"],
		"Middle Tennessee": [2, "Conference USA"],
		"Milwaukee": [0.1, "Horizon"],
		"Minnesota": [49, "Big Ten"],
		"Mississippi State": [18, "SEC"],
		"Mississippi Valley State": [1, "SWAC"],
		"Missouri": [32, "SEC"],
		"Missouri State": [5, "Conference USA"],
		"Monmouth": [1, "CAA"],
		"Montana": [5, "Big Sky"],
		"Montana State": [1, "Big Sky"],
		"Morehead State": [6, "Ohio Valley"],
		"Morgan State": [1, "MEAC"],
		"Mount St. Mary's": [2, "MAAC"],
		"Murray State": [12, "Missouri Valley"],
		"N.J.I.T.": [0.1, "America East"],
		"Navy": [2, "Patriot"],
		"Nebraska": [13, "Big Ten"],
		"Nebraska-Omaha": [0.1, "Summit"],
		"Nevada": [12, "Mountain West"],
		"New Hampshire": [0.1, "America East"],
		"New Mexico": [22, "Mountain West"],
		"New Mexico State": [16, "Conference USA"],
		"New Orleans": [8, "Southland"],
		"Niagara": [11, "MAAC"],
		"Nicholls State": [2, "Southland"],
		"Norfolk State": [5, "MEAC"],
		"North Alabama": [0.1, "ASUN"],
		"North Carolina": [97, "ACC"],
		"North Carolina A&T": [5, "CAA"],
		"North Carolina Central": [3, "MEAC"],
		"North Carolina State": [48, "ACC"],
		"North Carolina-Wilmington": [2, "CAA"],
		"North Dakota": [2, "Summit"],
		"North Dakota State": [0.1, "Summit"],
		"North Florida": [0.1, "ASUN"],
		"North Texas": [5, "American"],
		"Northeastern": [5, "CAA"],
		"Northern Arizona": [3, "Big Sky"],
		"Northern Colorado": [1, "Big Sky"],
		"Northern Illinois": [8, "MAC"],
		"Northern Iowa": [0.1, "Missouri Valley"],
		"Northern Kentucky": [0.1, "Horizon"],
		"Northwestern": [18, "Big Ten"],
		"Northwestern State": [2, "Southland"],
		"Notre Dame": [59, "ACC"],
		"Oakland": [4, "Horizon"],
		"Ohio": [10, "MAC"],
		"Ohio State": [47, "Big Ten"],
		"Oklahoma": [25, "SEC"],
		"Oklahoma State": [28, "Big 12"],
		"Old Dominion": [9, "Sun Belt"],
		"Ole Miss": [9, "SEC"],
		"Oral Roberts": [9, "Summit"],
		"Oregon": [31, "Big Ten"],
		"Oregon State": [29, "WCC"],
		"Pacific": [8, "WCC"],
		"Penn State": [14, "Big Ten"],
		"Pennsylvania": [11, "Ivy"],
		"Pepperdine": [19, "WCC"],
		"Pittsburgh": [22, "ACC"],
		"Portland": [8, "WCC"],
		"Portland State": [2, "Big Sky"],
		"Prairie View A&M": [2, "SWAC"],
		"Presbyterian": [0.1, "Big South"],
		"Princeton": [9, "Ivy"],
		"Providence": [30, "Big East"],
		"Purdue": [38, "Big Ten"],
		"Purdue Fort Wayne": [1, "Horizon"],
		"Quinnipiac": [0.1, "MAAC"],
		"Radford": [1, "Big South"],
		"Rhode Island": [17, "Atlantic 10"],
		"Rice": [12, "American"],
		"Richmond": [3, "Atlantic 10"],
		"Rider": [2, "MAAC"],
		"Robert Morris": [1, "Horizon"],
		"Rutgers": [13, "Big Ten"],
		"SIU-Edwardsville": [0.1, "Ohio Valley"],
		"SMU": [17, "ACC"],
		"Sacramento State": [0.1, "Big Sky"],
		"Sacred Heart": [0.1, "MAAC"],
		"Saint Joseph's (PA)": [21, "Atlantic 10"],
		"Saint Louis": [15, "Atlantic 10"],
		"Saint Mary's": [7, "WCC"],
		"Sam Houston State": [2, "Conference USA"],
		"Samford": [0.1, "Southern"],
		"San Diego": [1, "WCC"],
		"San Diego State": [12, "Mountain West"],
		"San Francisco": [25, "WCC"],
		"San Jose State": [9, "Mountain West"],
		"Santa Clara": [14, "WCC"],
		"Seattle": [11, "WAC"],
		"Seton Hall": [28, "Big East"],
		"Siena": [1, "MAAC"],
		"South Alabama": [5, "Sun Belt"],
		"South Carolina": [26, "SEC"],
		"South Carolina State": [3, "MEAC"],
		"South Dakota": [1, "Summit"],
		"South Dakota State": [3, "Summit"],
		"South Florida": [6, "American"],
		"Southeast Missouri State": [2, "Ohio Valley"],
		"Southeastern Louisiana": [0.1, "Southland"],
		"Southern Illinois": [10, "Missouri Valley"],
		"Southern Miss": [5, "Sun Belt"],
		"Southern University": [6, "SWAC"],
		"Southern Utah": [0.1, "WAC"],
		"St. Bonaventure": [17, "Atlantic 10"],
		"St. Francis (BKN)": [1, "NEC"],
		"St. Francis (PA)": [5, "NEC"],
		"St. John's": [54, "Big East"],
		"St. Peter's": [4, "MAAC"],
		"Stanford": [32, "ACC"],
		"Stephen F. Austin": [2, "Southland"],
		"Stetson": [2, "ASUN"],
		"Stony Brook": [1, "CAA"],
		"Syracuse": [53, "ACC"],
		"TCU": [10, "Big 12"],
		"Temple": [35, "American"],
		"Tennessee": [39, "SEC"],
		"Tennessee State": [19, "Ohio Valley"],
		"Tennessee Tech": [4, "Ohio Valley"],
		"Tennessee-Martin": [1, "Ohio Valley"],
		"Texas": [34, "SEC"],
		"Texas A&M": [17, "SEC"],
		"Texas A&M-CC": [0.1, "Southland"],
		"Texas Rio Grande Valley": [0.1, "WAC"],
		"Texas Southern": [5, "SWAC"],
		"Texas State": [2, "Sun Belt"],
		"Texas Tech": [14, "Big 12"],
		"Texas-Arlington": [1, "WAC"],
		"Toledo": [11, "MAC"],
		"Towson": [3, "CAA"],
		"Troy": [0.1, "Sun Belt"],
		"Tulane": [14, "American"],
		"Tulsa": [18, "American"],
		"UAB": [10, "American"],
		"UC Davis": [0.1, "Big West"],
		"UC Irvine": [8, "Big West"],
		"UC Riverside": [1, "Big West"],
		"UC Santa Barbara": [9, "Big West"],
		"UCF": [8, "Big 12"],
		"UCLA": [99, "Big Ten"],
		"UMBC": [0.1, "America East"],
		"UNC Asheville": [0.1, "Big South"],
		"UNC Greensboro": [0.1, "Southern"],
		"UNLV": [41, "Mountain West"],
		"USC": [44, "Big Ten"],
		"USC Upstate": [2, "Big South"],
		"UTEP": [17, "Conference USA"],
		"UTSA": [2, "American"],
		"Utah": [31, "Big 12"],
		"Utah State": [9, "Mountain West"],
		"Utah Valley": [3, "WAC"],
		"VCU": [10, "Atlantic 10"],
		"Valparaiso": [7, "Missouri Valley"],
		"Vanderbilt": [27, "SEC"],
		"Vermont": [0.1, "America East"],
		"Villanova": [49, "Big East"],
		"Virginia": [31, "ACC"],
		"Virginia Military": [2, "Southern"],
		"Virginia Tech": [16, "ACC"],
		"Wagner": [0.1, "NEC"],
		"Wake Forest": [31, "ACC"],
		"Washington": [39, "Big Ten"],
		"Washington State": [17, "WCC"],
		"Weber State": [10, "Big Sky"],
		"West Virginia": [16, "Big 12"],
		"Western Carolina": [7, "Southern"],
		"Western Illinois": [1, "Ohio Valley"],
		"Western Kentucky": [33, "Conference USA"],
		"Western Michigan": [7, "MAC"],
		"Wichita State": [19, "American"],
		"William & Mary": [2, "CAA"],
		"Winthrop": [0.1, "Big South"],
		"Wisconsin": [27, "Big Ten"],
		"Wofford": [1, "Southern"],
		"Wright State": [2, "Horizon"],
		"Wyoming": [25, "Mountain West"],
		"Xavier": [20, "Big East"],
		"Yale": [4, "Ivy"],
		"Youngstown State": [0.1, "Horizon"],
	};

	/* Destinations for players whose college is blank ("None" in game).

	   `strength` is the level of competition on the same 0-100 team scale.
	   `w` is the default weight in the blank-college draw, and `regions` scales
	   it by where the player was born — a Serbian leans EuroLeague and the ABA,
	   an Australian leans NBL and NBL1, a Chinese prospect leans CBA.

	   Before this there were exactly three destinations plus a rare DII roll,
	   which meant every blank-college prospect in the world went to one of
	   EuroLeague, the G League or the NBL. Liga ACB, the BBL, the Adriatic
	   League, LNB Pro A, the EuroCup, the CBA, NBL1, Overtime Elite and the NBA
	   Academies are all real destinations for exactly this population. */
	const NON_NCAA = {
		"EuroLeague":     { strength: 88, pro: true, w: 26, tier: 1,
			regions: { usa: 0.35, europe: 2.4, oceania: 0.5, asia: 0.4, latam: 0.6, africa: 0.7, other: 1.0 } },
		"NBA G League":   { strength: 84, pro: true, w: 30, tier: 1,
			regions: { usa: 1.7, europe: 0.5, oceania: 0.6, asia: 0.5, latam: 0.9, africa: 0.8, other: 1.0 } },
		"Liga ACB":       { strength: 80, pro: true, w: 10, tier: 2, domestic: "Spain", relegation: 2,
			regions: { usa: 0.2, europe: 1.5, oceania: 0.2, asia: 0.2, latam: 1.4, africa: 0.9, other: 0.7 } },
		"NBL":            { strength: 80, pro: true, w: 12, tier: 1,
			regions: { usa: 0.3, europe: 0.2, oceania: 2.6, asia: 0.6, latam: 0.2, africa: 0.3, other: 0.7 } },
		"Chinese CBA":    { strength: 78, pro: true, w: 6, tier: 2, domestic: "China",
			regions: { usa: 0.2, europe: 0.15, oceania: 0.3, asia: 2.8, latam: 0.2, africa: 0.4, other: 0.4 } },
		"LNB Pro A":      { strength: 76, pro: true, w: 9, tier: 2, domestic: "France", relegation: 2,
			regions: { usa: 0.25, europe: 1.3, oceania: 0.2, asia: 0.2, latam: 0.4, africa: 1.5, other: 0.7 } },
		"EuroCup":        { strength: 76, pro: true, w: 9, tier: 2,
			regions: { usa: 0.3, europe: 1.6, oceania: 0.3, asia: 0.3, latam: 0.5, africa: 0.6, other: 0.8 } },
		"Basketball Bundesliga": { strength: 74, pro: true, w: 8, tier: 2, domestic: "Germany", relegation: 2,
			regions: { usa: 0.3, europe: 1.3, oceania: 0.2, asia: 0.2, latam: 0.3, africa: 0.6, other: 0.7 } },
		"Adriatic League": { strength: 74, pro: true, w: 8, tier: 2,
			regions: { usa: 0.1, europe: 1.5, oceania: 0.1, asia: 0.1, latam: 0.2, africa: 0.3, other: 0.5 } },
		"NBL1":           { strength: 58, pro: true, w: 4, tier: 3, domestic: "Australia",
			regions: { usa: 0.2, europe: 0.1, oceania: 2.2, asia: 0.3, latam: 0.1, africa: 0.2, other: 0.4 } },
		"Overtime Elite": { strength: 46, pro: true, w: 5, tier: 3, youth: true,
			regions: { usa: 1.6, europe: 0.4, oceania: 0.5, asia: 0.4, latam: 0.6, africa: 0.9, other: 0.8 } },
		"NBA Academy":    { strength: 40, pro: false, w: 4, tier: 3, youth: true,
			regions: { usa: 0.2, europe: 0.4, oceania: 1.1, asia: 1.6, latam: 1.6, africa: 2.0, other: 1.2 } },
		"DII NCAA":       { strength: 38, pro: false, w: 0, tier: 3,
			regions: { usa: 1, europe: 0.2, oceania: 0.2, asia: 0.2, latam: 0.3, africa: 0.3, other: 0.3 } },
	};

	/* Real clubs for the non-NCAA destinations, so a prospect abroad gets a
	   team, a league table and a finish instead of a one-line note reading
	   "EuroLeague". `s` is a strength offset against the league's own level —
	   Real Madrid is not a relegation side. */
	const PRO_CLUBS = {
		"EuroLeague": [
			["Real Madrid", 9], ["FC Barcelona", 8], ["Panathinaikos", 7],
			["Olympiacos", 7], ["Fenerbahce", 6], ["Anadolu Efes", 5],
			["Maccabi Tel Aviv", 5], ["Zalgiris Kaunas", 3], ["Virtus Bologna", 3],
			["Olimpia Milano", 2], ["AS Monaco", 4], ["Baskonia", 1],
			["Partizan Belgrade", 2], ["Crvena Zvezda", 1], ["LDLC ASVEL", -2],
			["Alba Berlin", -3], ["Paris Basketball", -2], ["Bayern Munich", 0],
			["Valencia Basket", 0], ["Dubai BC", -4],
		],
		"NBA G League": [
			["Austin Spurs", 3], ["Rio Grande Valley Vipers", 3],
			["Santa Cruz Warriors", 2], ["Oklahoma City Blue", 2],
			["Raptors 905", 1], ["Long Island Nets", 1], ["Delaware Blue Coats", 1],
			["Sioux Falls Skyforce", 0], ["Wisconsin Herd", 0], ["Stockton Kings", 0],
			["Salt Lake City Stars", -1], ["Grand Rapids Gold", -1],
			["Maine Celtics", -1], ["Memphis Hustle", -2], ["Iowa Wolves", -2],
			["Westchester Knicks", -2], ["Cleveland Charge", -3],
			["Birmingham Squadron", -3], ["College Park Skyhawks", -3],
			["Capital City Go-Go", -4],
		],
		"Liga ACB": [
			["Real Madrid", 8], ["FC Barcelona", 7], ["Unicaja Malaga", 5],
			["Valencia Basket", 5], ["Baskonia", 4], ["Dreamland Gran Canaria", 2],
			["Joventut Badalona", 2], ["La Laguna Tenerife", 3],
			["UCAM Murcia", 0], ["Casademont Zaragoza", 0], ["Bilbao Basket", -1],
			["BAXI Manresa", -1], ["Basquet Girona", -2], ["MoraBanc Andorra", -3],
			["Rio Breogan", -3], ["Monbus Obradoiro", -4],
		],
		"NBL": [
			["Melbourne United", 4], ["Sydney Kings", 4], ["Perth Wildcats", 3],
			["New Zealand Breakers", 2], ["Illawarra Hawks", 1],
			["Tasmania JackJumpers", 1], ["Brisbane Bullets", -1],
			["Adelaide 36ers", -1], ["South East Melbourne Phoenix", -2],
			["Cairns Taipans", -3],
		],
		"Chinese CBA": [
			["Liaoning Flying Leopards", 6], ["Zhejiang Golden Bulls", 5],
			["Guangdong Southern Tigers", 5], ["Xinjiang Flying Tigers", 3],
			["Shenzhen Aviators", 2], ["Beijing Ducks", 1], ["Zhejiang Lions", 1],
			["Shanghai Sharks", 0], ["Shandong Heroes", 0], ["Shanxi Loongs", -1],
			["Jiangsu Dragons", -2], ["Qingdao Eagles", -2],
			["Nanjing Monkey Kings", -3], ["Sichuan Blue Whales", -3],
			["Fujian Sturgeons", -4], ["Tianjin Pioneers", -5],
		],
		"LNB Pro A": [
			["AS Monaco", 7], ["LDLC ASVEL", 5], ["Paris Basketball", 5],
			["Cholet Basket", 1], ["Nanterre 92", 1], ["Le Mans Sarthe", 1],
			["SIG Strasbourg", 0], ["JDA Dijon", 0], ["Limoges CSP", -1],
			["JL Bourg", 2], ["BCM Gravelines-Dunkerque", -2], ["Chorale Roanne", -2],
			["Saint-Quentin", -2], ["ESSM Le Portel", -3], ["SLUC Nancy", -3],
			["Elan Chalon", -3],
		],
		"EuroCup": [
			["Dreamland Gran Canaria", 4], ["Turk Telekom", 3], ["Buducnost", 2],
			["Joventut Badalona", 3], ["Bahcesehir Koleji", 2],
			["Cedevita Olimpija", 1], ["London Lions", 0], ["Aris Midea", 0],
			["Trento", 0], ["Veolia Towers Hamburg", -1], ["Wolves Twinsbet", -1],
			["Slask Wroclaw", -2], ["U-BT Cluj-Napoca", -1], ["Trefl Sopot", -3],
			["Besiktas", -2], ["Hapoel Jerusalem", 1],
		],
		"Basketball Bundesliga": [
			["Bayern Munich", 6], ["Alba Berlin", 4], ["Ratiopharm Ulm", 3],
			["Telekom Baskets Bonn", 3], ["MHP Riesen Ludwigsburg", 1],
			["Wurzburg Baskets", 1], ["Niners Chemnitz", 1],
			["Basketball Lowen Braunschweig", -1], ["EWE Baskets Oldenburg", 0],
			["Veolia Towers Hamburg", -1], ["BG Gottingen", -2],
			["Bamberg Baskets", -1], ["Skyliners Frankfurt", -2],
			["MLP Academics Heidelberg", -3], ["Rostock Seawolves", -3],
			["Hakro Merlins Crailsheim", -4],
		],
		"Adriatic League": [
			["Crvena Zvezda", 7], ["Partizan Belgrade", 7], ["Buducnost", 3],
			["Cedevita Olimpija", 2], ["Igokea", 0], ["Zadar", 0], ["Cibona", -1],
			["Split", -2], ["Mega Basket", 1], ["FMP Beograd", -1],
			["Borac Cacak", -2], ["Studentski Centar", -3], ["Krka", -3],
			["Spartak Subotica", -4],
		],
		"NBL1": [
			["Melbourne Tigers", 3], ["Nunawading Spectres", 2],
			["Basketball Australia CoE", 2], ["Ringwood Hawks", 1],
			["Frankston Blues", 0], ["Geelong Supercats", 0], ["Bendigo Braves", 0],
			["Sandringham Sabres", -1], ["Knox Raiders", -1],
			["Perth Redbacks", -1], ["Joondalup Wolves", -2],
			["Lakeside Lightning", -2], ["Norths Bears", -2],
			["Sutherland Sharks", -3], ["Bankstown Bruins", -3],
			["Brisbane Capitals", -3],
		],
		"Overtime Elite": [
			["City Reapers", 2], ["Cold Hearts", 1], ["YNG Dreamerz", 0],
			["RWE", 0], ["Diamond Doves", -1], ["Fear of God Athletics", -1],
		],
		"NBA Academy": [
			["NBA Global Academy", 3], ["NBA Academy Africa", 1],
			["NBA Academy Latin America", 0], ["NBA Academy India", -2],
			["NBA Academy Mexico City", -1],
		],
		"DII NCAA": [
			["Northwest Missouri State", 6], ["Nova Southeastern", 5],
			["Minnesota State", 4], ["West Liberty", 3], ["Black Hills State", 2],
			["Indiana (PA)", 2], ["Cal State San Bernardino", 1],
			["Augusta University", 0], ["Lincoln Memorial", 0],
			["Colorado School of Mines", -1], ["Bentley", -2], ["Barry", -2],
			["West Texas A&M", -3], ["Fort Hays State", -3], ["Queens (NC)", -4],
			["Angelo State", -5],
		],
	};

	// Countries/regions that read as European for EuroLeague weighting.
	const EURO_HINTS = [
		"Spain","Serbia","France","Italy","Greece","Lithuania","Slovenia","Croatia",
		"Turkey","Germany","Russia","Montenegro","Bosnia","Latvia","Estonia","Poland",
		"Czech","Ukraine","Israel","Georgia","Finland","Sweden","Norway","Denmark",
		"Netherlands","Belgium","Switzerland","Austria","Portugal","Hungary","Romania",
		"Bulgaria","Slovakia","North Macedonia","Kosovo","Albania","England","Scotland",
		"Ireland","Wales","Iceland","Cyprus","Armenia",
	];
	const OCEANIA_HINTS = ["Australia","New Zealand","Fiji","Samoa","Tonga","Papua"];
	const ASIA_HINTS = [
		"China","Japan","Korea","Philippines","Taiwan","Iran","India","Lebanon",
		"Indonesia","Kazakhstan","Jordan","Vietnam","Thailand","Malaysia",
		"Singapore","Mongolia","Syria","Qatar","Emirates","Saudi",
	];
	const LATAM_HINTS = [
		"Brazil","Argentina","Mexico","Dominican","Puerto Rico","Venezuela",
		"Colombia","Chile","Uruguay","Panama","Cuba","Bahamas","Jamaica",
		"Haiti","Trinidad","Ecuador","Peru","Bolivia","Paraguay","Guatemala",
		"Honduras","Costa Rica","Virgin Islands",
	];
	const AFRICA_HINTS = [
		"Nigeria","Senegal","Cameroon","Congo","Sudan","Mali","Angola","Egypt",
		"Tunisia","Morocco","Algeria","Ghana","Kenya","Ivory Coast","Guinea",
		"South Africa","Rwanda","Uganda","Tanzania","Zimbabwe","Burkina",
		"Benin","Togo","Gabon","Chad","Niger","Somalia","Ethiopia","Libya",
	];

	function isUSA(loc) {
		return typeof loc === "string" && /USA$/.test(loc);
	}
	function region(loc) {
		if (isUSA(loc)) return "usa";
		const s = String(loc || "");
		if (EURO_HINTS.some((h) => s.indexOf(h) !== -1)) return "europe";
		if (OCEANIA_HINTS.some((h) => s.indexOf(h) !== -1)) return "oceania";
		if (AFRICA_HINTS.some((h) => s.indexOf(h) !== -1)) return "africa";
		if (LATAM_HINTS.some((h) => s.indexOf(h) !== -1)) return "latam";
		if (ASIA_HINTS.some((h) => s.indexOf(h) !== -1)) return "asia";
		if (/Canada/.test(s)) return "usa";
		return "other";
	}

	/* Weight of one non-NCAA destination for a player born in `loc`. */
	function leagueWeight(name, loc, override) {
		const lg = NON_NCAA[name];
		if (!lg) return 0;
		const base = Number.isFinite(override) ? override : lg.w;
		const mult = (lg.regions && lg.regions[region(loc)]) !== undefined
			? lg.regions[region(loc)]
			: 1;
		return Math.max(0, base) * mult;
	}

	const conferenceOf = (name) => (COLLEGES[name] ? COLLEGES[name][1] : null);
	const frequencyOf = (name) => (COLLEGES[name] ? COLLEGES[name][0] : 1);

	// Program prestige 0-100 from BBGM draft frequency (log-scaled: Kentucky 116
	// and Wagner 0.1 should not be 1000x apart in on-court terms).
	function prestige(name) {
		const f = frequencyOf(name);
		const p = (Math.log(f + 0.6) - Math.log(0.7)) / (Math.log(116.6) - Math.log(0.7));
		return Math.max(0, Math.min(1, p)) * 100;
	}

	const byConference = {};
	for (const name of Object.keys(COLLEGES)) {
		const c = COLLEGES[name][1];
		(byConference[c] = byConference[c] || []).push(name);
	}

	global.Colleges = {
		COLLEGES, CONFERENCES, NON_NCAA, PRO_CLUBS, byConference,
		conferenceOf, frequencyOf, prestige, region, isUSA, leagueWeight,
		names: Object.keys(COLLEGES),
	};
})(typeof window !== "undefined" ? window : self);
